full_name = input("enter name :")
age = int(input("enter age:"))
height = float(input("enter height:"))
favorite_language = input("enter language:")
coding_experience = int(input("enter experiance:"))
currently_learning_python = True

print(" Personal Information ")
print(f"Full Name: {full_name}")
print(f"Age: {age}")
print(f"Height: {height} meters")
print(f"Favorite Programming Language: {favorite_language}")
print(f"Years of Coding Experience: {coding_experience}")
print(f"Currently Learning Python: {currently_learning_python}")
print("\nData Types")
print(f"Full Name Type: {type(full_name)}")
print(f"Age Type: {type(age)}")
print(f"Height Type: {type(height)}")
print(f"Favorite Language Type: {type(favorite_language)}")
print(f"Coding Experience Type: {type(coding_experience)}")
print(f"Currently Learning Python Type: {type(currently_learning_python)}")